cdlaid_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: cdlaid_user
      password: CdlaidDB2025!Strong
      database: cdlaid_analytics
      schema: mart
      threads: 4
    school:
      type: postgres
      host: localhost
      port: 5433
      user: cdlaid_user
      password: CdlaidDB2025!Strong
      database: cdlaid_school
      schema: mart
      threads: 2